FROM maven
#copy the source tree and pom.xml to our new container
COPY ./ ./
#package our application code
RUN mvn clean package
#set the startup command to execute the jar file
ENTRYPOINT ["java","-jar","target/usermanagement-0.0.1-SNAPSHOT.jar"]
